spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: localhost
    username: root
    password: 1234

jwt:
  token:
    secret: hello.zz.rr.ff.tt